import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { Roboto } from 'next/font/google';

const roboto400 = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto400.className}>{children}</body>
    </html>
  );
}
